language: node_js
sudo: false
node_js:
  - stable
  - lts/carbon
install: npm install
before_install:
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
before_script: if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
script: if [[ $GH_TOKEN ]]; then npm test; fi;
cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

stages:
  - Test
  - name: Release
    if: branch = master

jobs:
  include:
  - stage: Release
    node_js: lts/*
    before_install: []
    script: if [[ $GH_TOKEN ]]; then semantic-release; fi;
    after_script: []