language: node_js
sudo: false
node_js:
  - stable
  - lts/carbon
  - lts/boron
install: npm install
before_install:
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
cache:
  directories:
  - node_modules
before_cache: rm -rf node_modules/.cache
