language: node_js
sudo: false
node_js:
  - stable
  - lts/carbon
  - lts/boron
install: npm install
before_install:
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
cache:
  directories:
    - node_modules
before_cache: rm -rf node_modules/.cache
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

stages:
  - Test
  - name: Release
    if: branch = master

jobs:
  include:
  - stage: Release
    node_js: stable
    before_install: []
    script: semantic-release
    after_script: []