name: Core
on:
  push:
    branches: [master]
  pull_request: {}
  
permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM Init
        uses: ./.github/actions/init-npm
      - name: Test
        run: npm run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          persist-credentials: false
      - name: Init NPM
        uses: ./.github/actions/init-npm
      - uses: actions/setup-node@v3
        name: Reconfig Node
        with:
          registry-url: https://registry.npmjs.org
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
